In [4]:
import pandas as pd
import numpy as np

In [5]:
raw_call = pd.read_csv("class_data_2023.csv")
raw_weather = pd.read_csv("Eugene Oregon 2023-08-10 to 2025-04-25.csv")

C:\Users\trema\AppData\Local\Temp\ipykernel_28360\2622061745.py:1: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  raw_call = pd.read_csv("class_data_2023.csv")

In [6]:
raw_call.head()

,yr,service,inci_id,calltime,case_id,callsource,nature,closecode,closed_as,secs_to_disp,secs_to_arrv,secs_to_close,disp,arrv,beat,priority,zip,primeunit,units_dispd,units_arrived
0,2023,LAW,23000008,2023-01-01 00:03:23.000,NaN,SELF,SPEEDING MOTORCYCLE,UTC,UNIFORM TRAFFIC CITATION ISSUED,0.0,0.0,1258,1,1,EP01,P,,6E57,2,2
1,2023,LAW,23000013,2023-01-01 00:04:56.000,NaN,W911,ILLEGAL FIREWORKS,REL,REFERRED TO OTHER AGENCY,NaN,NaN,37,0,0,EP06,5,,NaN,0,0
2,2023,LAW,23000015,2023-01-01 00:05:55.000,NaN,PHONE,CRIMINAL MISCHIEF,ADVI,ADVISED,NaN,NaN,91,0,0,EP01,P,,NaN,0,0
3,2023,LAW,23000019,2023-01-01 00:10:04.000,NaN,SELF,PATROL CHECK,PCHK,PATROL CHECK,0.0,0.0,970,1,1,EP02,6,,4F71,2,2
4,2023,LAW,23000021,2023-01-01 00:11:05.000,NaN,SELF,PATROL CHECK,PCHK,PATROL CHECK,0.0,0.0,791,1,1,EP07,6,,4E36,1,1

In [7]:
raw_weather.head()

,datetime,tempmax,tempmin,temp,feelslike,dew,humidity,precip,precipprob,precipcover,...,windspeedmin,winddir,sealevelpressure,solarradiation,solarenergy,uvindex,severerisk,conditions,description,source
0,2023-08-10,83.9,62.9,72.8,72.5,54.5,55.6,0.0,0,0.0,...,0.5,309.1,1015.1,267.9,22.9,9,10,Partially cloudy,Clearing in the afternoon.,obs
1,2023-08-11,89.0,56.9,72.3,71.7,53.3,55.0,0.0,0,0.0,...,0.0,311.9,1016.4,303.5,26.2,9,10,Clear,Clear conditions throughout the day.,obs
2,2023-08-12,91.1,58.0,74.6,74.0,54.2,52.8,0.0,0,0.0,...,0.4,317.4,1018.8,295.4,25.8,9,10,Partially cloudy,Partly cloudy throughout the day.,obs
3,2023-08-13,101.8,62.8,80.7,79.9,54.9,46.0,0.0,0,0.0,...,0.2,312.8,1015.4,286.0,24.5,8,10,Partially cloudy,Partly cloudy throughout the day.,obs
4,2023-08-14,102.0,65.7,83.3,82.6,55.3,41.9,0.0,0,0.0,...,0.0,329.0,1011.8,228.3,19.6,7,10,Partially cloudy,Partly cloudy throughout the day.,obs

In [8]:
raw_weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 625 entries, 0 to 624
Data columns (total 27 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   datetime          625 non-null    object
 1   tempmax           625 non-null    float64
 2   tempmin           625 non-null    float64
 3   temp              625 non-null    float64
 4   feelslike         625 non-null    float64
 5   dew               625 non-null    float64
 6   humidity          625 non-null    float64
 7   precip            625 non-null    float64
 8   precipprob        625 non-null    int64
 9   precipcover       625 non-null    float64
 10  preciptype        298 non-null    object
 11  snow              625 non-null    float64
 12  snowdepth         625 non-null    float64
 13  windgust          625 non-null    float64
 14  windspeed         625 non-null    float64
 15  windspeedmax      625 non-null    float64
 16  windspeedmean     625 non-null    float64
 17  windspeedmin      625 non-null    float64
 18  winddir           625 non-null    float64
 19  sealevelpressure  625 non-null    float64
 20  solarradiation    625 non-null    float64
 21  solarenergy       625 non-null    float64
 22  uvindex           625 non-null    int64
 23  severerisk        625 non-null    int64
 24  conditions        625 non-null    object
 25  description       625 non-null    object
 26  source            625 non-null    object
dtypes: float64(19), int64(3), object(5)
memory usage: 132.0+ KB

In [11]:
raw_call.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135464 entries, 0 to 135463
Data columns (total 20 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   yr             135464 non-null  int64
 1   service        135464 non-null  object
 2   inci_id        135464 non-null  int64
 3   calltime       135464 non-null  object
 4   case_id        20018 non-null   float64
 5   callsource     135464 non-null  object
 6   nature         135454 non-null  object
 7   closecode      135464 non-null  object
 8   closed_as      132932 non-null  object
 9   secs_to_disp   94905 non-null   float64
 10  secs_to_arrv   80815 non-null   float64
 11  secs_to_close  135464 non-null  int64
 12  disp           135464 non-null  int64
 13  arrv           135464 non-null  int64
 14  beat           135462 non-null  object
 15  priority       135464 non-null  object
 16  zip            135464 non-null  object
 17  primeunit      100317 non-null  object
 18  units_dispd    135464 non-null  int64
 19  units_arrived  135464 non-null  int64
dtypes: float64(3), int64(7), object(10)
memory usage: 20.7+ MB

In [10]:
raw_call['PrimaryUnitCallSign'].value_counts()

KeyError: 'PrimaryUnitCallSign'

In [ ]:
raw_call['Call_Created_Time'].max()

'8/9/23 9:59'